from datetime import datetime, timedelta

from homeward.models.case import (
    CasePriority,
    CaseStatus,
    SightingConfidenceLevel,
    SightingSourceType,
    SightingStatus,
    KPIData,
    Location,
    MissingPersonCase,
    Sighting,
)


def get_mock_cases():
    """Generate mock missing person cases for demonstration"""
    return [
        MissingPersonCase(
            id="MP001",
            name="Mario",
            surname="Rossi",
            date_of_birth=datetime(1990, 6, 15),
            gender="Male",
            last_seen_date=datetime.now() - timedelta(days=2),
            last_seen_location=Location(
                address="Via Roma 15",
                city="Milano",
                country="Italy",
                postal_code="20121",
                latitude=45.4654,
                longitude=9.1859,
            ),
            status=CaseStatus.ACTIVE,
            circumstances="Failed to return home after evening walk",
            description="Active professional who regularly walks in the evening. Has no history of going missing.",
            reporter_name="Elena Rossi",
            reporter_phone="+39 333 1234567",
            relationship="Wife",
            case_number="CASE-2025-0901-0001",
            height=175.0,
            weight=75.0,
            hair_color="Brown",
            eye_color="Blue",
            clothing_description="Blue jeans and red jacket",
            reporter_email="elena.rossi@email.com",
            priority=CasePriority.HIGH,
        ),
        MissingPersonCase(
            id="MP002",
            name="Anna",
            surname="Bianchi",
            date_of_birth=datetime(1996, 3, 22),
            gender="Female",
            last_seen_date=datetime.now() - timedelta(days=1),
            last_seen_location=Location(
                address="Corso Buenos Aires 45",
                city="Milano",
                country="Italy",
                postal_code="20124",
                latitude=45.4773,
                longitude=9.2009,
            ),
            status=CaseStatus.ACTIVE,
            circumstances="Did not arrive at scheduled meeting with friends",
            reporter_name="Marco Bianchi",
            reporter_phone="+39 335 2468135",
            relationship="Brother",
            case_number="CASE-2025-0902-0001",
            height=165.0,
            weight=60.0,
            hair_color="Blonde",
            eye_color="Green",
            clothing_description="Black coat and white sneakers",
            priority=CasePriority.MEDIUM,
        ),
        MissingPersonCase(
            id="MP003",
            name="Giuseppe",
            surname="Verdi",
            date_of_birth=datetime(1957, 8, 10),
            gender="Male",
            last_seen_date=datetime.now() - timedelta(days=5),
            last_seen_location=Location(
                address="Piazza Duomo 1",
                city="Milano",
                country="Italy",
                postal_code="20122",
                latitude=45.4640,
                longitude=9.1895,
            ),
            status=CaseStatus.ACTIVE,
            circumstances="Left nursing home without notification",
            reporter_name="Lucia Verdi",
            reporter_phone="+39 347 3691258",
            relationship="Daughter",
            case_number="CASE-2025-0903-0001",
            height=170.0,
            weight=65.0,
            hair_color="Gray",
            eye_color="Brown",
            distinguishing_marks="Scar on left hand",
            clothing_description="Brown coat, walking stick",
            medical_conditions="Early stage dementia",
            priority=CasePriority.HIGH,
        ),
        MissingPersonCase(
            id="MP004",
            name="Elena",
            surname="Ferrari",
            date_of_birth=datetime(2008, 12, 5),
            gender="Female",
            last_seen_date=datetime.now() - timedelta(hours=8),
            last_seen_location=Location(
                address="Via Torino 23",
                city="Milano",
                country="Italy",
                postal_code="20123",
                latitude=45.4612,
                longitude=9.1844,
            ),
            status=CaseStatus.ACTIVE,
            circumstances="Did not return home after school",
            reporter_name="Maria Ferrari",
            reporter_phone="+39 339 1472583",
            relationship="Mother",
            case_number="CASE-2025-0904-0001",
            height=160.0,
            weight=55.0,
            hair_color="Brown",
            eye_color="Blue",
            clothing_description="School uniform and backpack",
            priority=CasePriority.HIGH,
        ),
        MissingPersonCase(
            id="MP005",
            name="Francesco",
            surname="Bruno",
            date_of_birth=datetime(1982, 4, 18),
            gender="Male",
            last_seen_date=datetime.now() - timedelta(days=3),
            last_seen_location=Location(
                address="Via Dante 8",
                city="Milano",
                country="Italy",
                postal_code="20121",
                latitude=45.4654,
                longitude=9.1859,
            ),
            status=CaseStatus.ACTIVE,
            circumstances="Failed to return from business meeting",
            reporter_name="Silvia Bruno",
            reporter_phone="+39 340 2583697",
            relationship="Wife",
            case_number="CASE-2025-0905-0001",
            height=180.0,
            weight=80.0,
            hair_color="Black",
            eye_color="Brown",
            clothing_description="Grey suit and black shoes",
            priority=CasePriority.MEDIUM,
        ),
        MissingPersonCase(
            id="MP006",
            name="Laura",
            surname="Conte",
            date_of_birth=datetime(1993, 11, 7),
            gender="Female",
            last_seen_date=datetime.now() - timedelta(days=4),
            last_seen_location=Location(
                address="Viale Monza 120",
                city="Milano",
                country="Italy",
                postal_code="20127",
                latitude=45.4773,
                longitude=9.2009,
            ),
            status=CaseStatus.ACTIVE,
            circumstances="Disappeared during evening jog",
            reporter_name="Andrea Conte",
            reporter_phone="+39 366 9517428",
            relationship="Husband",
            case_number="CASE-2025-0906-0001",
            height=168.0,
            weight=58.0,
            hair_color="Red",
            eye_color="Green",
            clothing_description="Green dress",
            priority=CasePriority.LOW,
        ),
        MissingPersonCase(
            id="MP007",
            name="Marco",
            surname="Galli",
            date_of_birth=datetime(1999, 9, 14),
            gender="Male",
            last_seen_date=datetime.now() - timedelta(days=1),
            last_seen_location=Location(
                address="Via Brera 12",
                city="Milano",
                country="Italy",
                postal_code="20121",
                latitude=45.4640,
                longitude=9.1895,
            ),
            status=CaseStatus.ACTIVE,
            circumstances="Did not return from morning run",
            reporter_name="Paolo Galli",
            reporter_phone="+39 333 7418529",
            relationship="Brother",
            case_number="CASE-2025-0907-0001",
            height=185.0,
            weight=75.0,
            hair_color="Brown",
            eye_color="Blue",
            clothing_description="Sports clothes",
            priority=CasePriority.HIGH,
        ),
        MissingPersonCase(
            id="MP008",
            name="Sofia",
            surname="Martini",
            date_of_birth=datetime(2005, 5, 28),
            gender="Female",
            last_seen_date=datetime.now() - timedelta(hours=12),
            last_seen_location=Location(
                address="Porta Garibaldi Station",
                city="Milano",
                country="Italy",
                postal_code="20124",
                latitude=45.4612,
                longitude=9.1844,
            ),
            status=CaseStatus.ACTIVE,
            circumstances="Did not board train home after classes",
            reporter_name="Francesca Martini",
            reporter_phone="+39 348 3692581",
            relationship="Mother",
            case_number="CASE-2025-0908-0001",
            height=162.0,
            weight=52.0,
            hair_color="Brown",
            eye_color="Brown",
            clothing_description="University student with purple backpack",
            priority=CasePriority.HIGH,
        ),
        MissingPersonCase(
            id="MP009",
            name="Roberto",
            surname="Lombardi",
            date_of_birth=datetime(1969, 1, 23),
            gender="Male",
            last_seen_date=datetime.now() - timedelta(days=6),
            last_seen_location=Location(
                address="Via Nazionale 45",
                city="Milano",
                country="Italy",
                postal_code="20123",
                latitude=45.4654,
                longitude=9.1859,
            ),
            status=CaseStatus.ACTIVE,
            circumstances="Failed to return home from work",
            reporter_name="Carla Lombardi",
            reporter_phone="+39 335 8529741",
            relationship="Wife",
            case_number="CASE-2025-0909-0001",
            height=175.0,
            weight=85.0,
            hair_color="Black",
            eye_color="Brown",
            clothing_description="Dark blue coat",
            priority=CasePriority.MEDIUM,
        ),
        MissingPersonCase(
            id="MP010",
            name="Giulia",
            surname="Romano",
            date_of_birth=datetime(2001, 7, 11),
            gender="Female",
            last_seen_date=datetime.now() - timedelta(days=2),
            last_seen_location=Location(
                address="Corso di Porta Romana 85",
                city="Milano",
                country="Italy",
                postal_code="20122",
                latitude=45.4773,
                longitude=9.2009,
            ),
            status=CaseStatus.ACTIVE,
            circumstances="Did not return from shopping trip",
            reporter_name="Luigi Romano",
            reporter_phone="+39 349 7410852",
            relationship="Father",
            case_number="CASE-2025-0910-0001",
            height=170.0,
            weight=60.0,
            hair_color="Blonde",
            eye_color="Blue",
            clothing_description="Yellow jacket",
            priority=CasePriority.MEDIUM,
        ),
        MissingPersonCase(
            id="MP011",
            name="Alessandro",
            surname="Ricci",
            date_of_birth=datetime(1986, 10, 2),
            gender="Male",
            last_seen_date=datetime.now() - timedelta(days=7),
            last_seen_location=Location(
                address="Via Moscova 28",
                city="Milano",
                country="Italy",
                postal_code="20121",
                latitude=45.4640,
                longitude=9.1895,
            ),
            status=CaseStatus.ACTIVE,
            circumstances="Did not return from weekend trip",
            reporter_name="Valentina Ricci",
            reporter_phone="+39 338 1596382",
            relationship="Wife",
            case_number="CASE-2025-0911-0001",
            height=178.0,
            weight=72.0,
            hair_color="Brown",
            eye_color="Green",
            distinguishing_marks="Beard",
            clothing_description="Leather jacket",
            priority=CasePriority.LOW,
        ),
        MissingPersonCase(
            id="MP012",
            name="Valentina",
            surname="Esposito",
            date_of_birth=datetime(1995, 2, 19),
            gender="Female",
            last_seen_date=datetime.now() - timedelta(days=3),
            last_seen_location=Location(
                address="Piazza Gae Aulenti 4",
                city="Milano",
                country="Italy",
                postal_code="20124",
                latitude=45.4612,
                longitude=9.1844,
            ),
            status=CaseStatus.ACTIVE,
            circumstances="Failed to return home after work",
            reporter_name="Matteo Esposito",
            reporter_phone="+39 346 2739485",
            relationship="Husband",
            case_number="CASE-2025-0912-0001",
            height=165.0,
            weight=57.0,
            hair_color="Brown",
            eye_color="Brown",
            clothing_description="White coat",
            reporter_email="matteo.esposito@email.com",
            priority=CasePriority.HIGH,
        ),
    ]


def get_mock_kpi_data():
    """Generate mock KPI data for dashboard"""
    return KPIData(
        total_cases=247,
        active_cases=12,
        resolved_cases=235,
        sightings_today=8,
        success_rate=95.2,
        avg_resolution_days=3.4,
    )


def get_mock_sightings():
    """Generate mock sighting reports for demonstration"""
    return [
        Sighting(
            id="S001",
            sighted_date=datetime.now() - timedelta(hours=3),
            sighted_location=Location(
                address="Via Montenapoleone 8",
                city="Milano",
                country="Italy",
                postal_code="20121",
                latitude=45.4685,
                longitude=9.1951,
            ),
            description="Man in blue jacket, approximately 34 years old, walking quickly towards metro station",
            confidence_level=SightingConfidenceLevel.HIGH,
            source_type=SightingSourceType.WITNESS,
            apparent_gender="Male",
            apparent_age_range="30-39",
            clothing_description="Blue jacket",
            status=SightingStatus.NEW,
            witness_name="Luca Bianchi",
            witness_email="luca.bianchi@email.com",
            witness_phone="+39 345 1234567",
            created_by="Luca Bianchi",
        ),
        Sighting(
            id="S002",
            sighted_date=datetime.now() - timedelta(hours=6),
            sighted_location=Location(
                address="Corso Buenos Aires 12",
                city="Milano",
                country="Italy",
                postal_code="20124",
                latitude=45.4798,
                longitude=9.2076,
            ),
            description="Young woman in black coat, appeared confused and asking for directions",
            confidence_level=SightingConfidenceLevel.MEDIUM,
            source_type=SightingSourceType.WITNESS,
            apparent_gender="Female",
            apparent_age_range="20-29",
            clothing_description="Black coat",
            status=SightingStatus.VERIFIED,
            verified=True,
            witness_name="Giulia Rossi",
            witness_email="giulia.rossi@email.com",
            created_by="Giulia Rossi",
        ),
        Sighting(
            id="S003",
            sighted_date=datetime.now() - timedelta(hours=12),
            sighted_location=Location(
                address="Piazza Duomo",
                city="Milano",
                country="Italy",
                postal_code="20122",
                latitude=45.4640,
                longitude=9.1895,
            ),
            description="Elderly man with walking stick, wearing brown coat, sitting on bench",
            confidence_level=SightingConfidenceLevel.HIGH,
            source_type=SightingSourceType.WITNESS,
            apparent_gender="Male",
            apparent_age_range="60-69",
            clothing_description="Brown coat",
            distinguishing_features="Walking stick",
            status=SightingStatus.VERIFIED,
            verified=True,
            witness_name="Marco Verdi",
            witness_email="marco.verdi@email.com",
            witness_phone="+39 331 9876543",
            created_by="Marco Verdi",
        ),
        Sighting(
            id="S004",
            sighted_date=datetime.now() - timedelta(hours=2),
            sighted_location=Location(
                address="Stazione Centrale",
                city="Milano",
                country="Italy",
                postal_code="20124",
                latitude=45.4864,
                longitude=9.2058,
            ),
            description="Teenager with backpack, school uniform, looked lost near train platform",
            confidence_level=SightingConfidenceLevel.HIGH,
            source_type=SightingSourceType.WITNESS,
            apparent_gender="Female",
            apparent_age_range="10-19",
            clothing_description="School uniform with backpack",
            status=SightingStatus.NEW,
            witness_name="Elena Ferrari",
            witness_email="elena.ferrari@email.com",
            created_by="Elena Ferrari",
        ),
        Sighting(
            id="S005",
            sighted_date=datetime.now() - timedelta(hours=8),
            sighted_location=Location(
                address="Via Brera 25",
                city="Milano",
                country="Italy",
                postal_code="20121",
                latitude=45.4720,
                longitude=9.1881,
            ),
            description="Tall athletic man in sports clothes, jogging in the area",
            confidence_level=SightingConfidenceLevel.MEDIUM,
            source_type=SightingSourceType.WITNESS,
            apparent_gender="Male",
            apparent_age_range="20-29",
            clothing_description="Sports clothes",
            distinguishing_features="Tall, athletic build",
            status=SightingStatus.NEW,
            witness_name="Alessandro Russo",
            witness_email="alessandro.russo@email.com",
            witness_phone="+39 333 4567890",
            created_by="Alessandro Russo",
        ),
        Sighting(
            id="S006",
            sighted_date=datetime.now() - timedelta(minutes=45),
            sighted_location=Location(
                address="Via Moscova 45",
                city="Milano",
                country="Italy",
                postal_code="20121",
                latitude=45.4752,
                longitude=9.1886,
            ),
            description="Young woman with purple backpack, appeared to be a university student",
            confidence_level=SightingConfidenceLevel.HIGH,
            source_type=SightingSourceType.WITNESS,
            apparent_gender="Female",
            apparent_age_range="18-25",
            clothing_description="Casual clothes with purple backpack",
            status=SightingStatus.NEW,
            witness_name="Anna Lombardi",
            witness_email="anna.lombardi@email.com",
            created_by="Anna Lombardi",
        ),
        Sighting(
            id="S007",
            sighted_date=datetime.now() - timedelta(hours=18),
            sighted_location=Location(
                address="Porta Garibaldi",
                city="Milano",
                country="Italy",
                postal_code="20124",
                latitude=45.4852,
                longitude=9.1877,
            ),
            description="Person in dark clothing, couldn't see clearly due to distance",
            confidence_level=SightingConfidenceLevel.LOW,
            source_type=SightingSourceType.WITNESS,
            apparent_gender="Unknown",
            clothing_description="Dark clothing",
            status=SightingStatus.FALSE_POSITIVE,
            witness_name="Roberto Galli",
            witness_email="roberto.galli@email.com",
            witness_phone="+39 347 2468135",
            created_by="Roberto Galli",
        ),
    ]
